# Generated by Django 4.1.1 on 2022-10-03 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin_data')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNum', models.CharField(max_length=9)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNum', models.CharField(max_length=9)),
                ('requesttype', models.CharField(blank=True, default='', max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('motivation', models.CharField(default='', max_length=120)),
                ('datefrom', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('dateTo', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('reason', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField(blank=True)),
                ('test2', models.IntegerField(blank=True)),
                ('assignment1', models.IntegerField(blank=True)),
                ('assignment2', models.IntegerField(blank=True)),
                ('assignment3', models.IntegerField(blank=True)),
                ('assignment4', models.IntegerField(blank=True)),
                ('assignment5', models.IntegerField(blank=True)),
                ('assignment6', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_current', to='database.student')),
            ],
        ),
        migrations.CreateModel(
            name='cs1Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField(blank=True)),
                ('test2', models.IntegerField(blank=True)),
                ('assignment1', models.IntegerField(blank=True)),
                ('assignment2', models.IntegerField(blank=True)),
                ('assignment3', models.IntegerField(blank=True)),
                ('assignment4', models.IntegerField(blank=True)),
                ('assignment5', models.IntegerField(blank=True)),
                ('assignment6', models.IntegerField(blank=True)),
                ('student0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_current_cs1', to='database.student')),
            ],
        ),
    ]
